### ISSUE TITLE
Support fo iPad

### ISSUE THREAD

**Issue by ghost** [hans/obsidian-citation-plugin#132] opened 2021-12-19 07:55 UTC
Are there any plans for adding support for iOS?
++Johan

**Comment by Benjamin-Lee** [comment] 2021-12-23 21:52
I tried installing it and was surprised to see it throw an error. I'm keeping my .bib in the workspace and using sync to share it so that I can work with my references on my iPad.

**Comment by arakotoz** [comment] 2022-01-11 22:11
> I tried installing it and was surprised to see it throw an error. I'm keeping my .bib in the workspace and using sync to share it so that I can work with my references on my iPad.

Hi, I have the same settings and ran in the same issue. It is working well on the Mac though.
Hoping that there will be a future support for iOS,
Cheers

**Comment by vaclavstepan** [comment] 2022-03-26 12:56
I'd love iOS support too. There seems to be discussion on this topic [here as well](https://githubhot.com/repo/hans/obsidian-citation-plugin/issues/118).

**Comment by hans** [comment] 2022-05-14 20:17
Closing as a duplicate of #118.

**Closed by hans** 2022-05-14 20:17 UTC
