### ISSUE TITLE
Newly added notes are not automatically updated 

### ISSUE THREAD

**Issue by jack1002020** [hans/obsidian-citation-plugin#107] opened 2021-08-02 18:17 UTC
Any changes I made in Zotero are not automatically updated by the citation plugin. I have to cut and paste the file location every single time. 

Obsidian: v0.12.10
Plugin: 0.4.3
MacOS: 11.5.1
Citation database format: BibLateX

**Comment by luke-thorburn** [comment] 2021-08-10 05:06
I also have this issue—restarting Obsidian also seems to trigger the citations to update. But it would be great if updates were automatically loaded.

**Comment by luke-thorburn** [comment] 2021-08-10 05:30
Actually, I've just been able to fix it. For me there was an error in the Obsidian Console (Cmd+Shift+I) that indicated there was an issue parsing the abstract of one of the references. I removed the abstract in Zotero and that fixed it.

**Comment by lukesmurray** [comment] 2021-08-10 12:55
This is fixed by #104. As a workaround you can try setting the citation file path as an absolute path.

**Comment by hans** [comment] 2021-08-20 16:29
Hi @jack1002020 , there should be a fix for this issue in the just-released [v0.4.4](https://github.com/hans/obsidian-citation-plugin/releases/tag/0.4.4). Please update and let me know here if the issue is not resolved for you. Thanks for your extreme patience!

**Closed by hans** 2021-08-20 16:29 UTC
