### ISSUE TITLE
Auto-updating with updated bibtex

### ISSUE THREAD

**Issue by lemywong** [hans/obsidian-citation-plugin#52] opened 2021-01-17 10:37 UTC
Thanks for this lovely plugin, but there's one thing I find inconvenient.

When the exported bibtex has been auto-updated by betterbibtex, the newly loaded items cannot be found until **reopening** obsidian, this would perhaps lower the efficiency for those who are intensively adding their bib while taking notes in obsidian. So, perhaps it would be much better to get the plugin in track with the changing bibtex/json files, but I'm not sure if this function is practical?

**Comment by hans** [comment] 2021-01-17 14:13
Hi @lemywong , thanks for trying out the plugin. What you are requesting
should already be the expected behavior. So it sounds like we have a bug.

Can you give me some information to help debug?

- what operating system are you using?
- what version of Obsidian and the Citations plugin are you using?
- in Obsidian, open the developer console (Ctrl Shift I) and then refresh
(Ctrl R). Do you see any messages appear within the first few seconds as
the citations load?

**Comment by n8craig** [comment] 2021-01-17 19:24
Just cross referencing to #34 as this seems really similar.

At my end, Win 10, Obsidian 10.7 and Citations 0.4.1, Better BibLaTex library file (ca 4k references), I'm not seeing anything in the console. (Crtl R) gets the newly entered citation to load so that the plugin can find it without completely restarting the application. However, upon calling up the search interface the plugin is slow to re-read the library database. It feels like it is reading in the whole database rather than just looking for changes. For instance, on a second search it pops up very quickly; I'm assuming because it is cached.

**Comment by lemywong** [comment] 2021-01-18 07:18
hi @hans thanks to your quick response, my situation is similar with @n8craig but I'll give you the details too
- the OS is win10
- Obsidian 10.8 and Citation 0.4.1 are used
- Refreshing results in 'loading markdown-table-editor plugin' in the developer console, this is another plugin I installed, and I only have Citation and Advance Table installed from the third party plugin

**Comment by claykaufmann** [comment] 2021-01-20 19:40
Would like to add-on here, on Mac with Obsidian 10.8, having the same issue. I found that if you re-enter the path to the exported citation library this also updates it, however I assume that this is still not the fully expected behavior

**Comment by frankreporting** [comment] 2021-03-16 23:30
I may have found a clue, if it helps.

I was having a similar (but worse?) problem. I tried other workarounds listed: i.e. restart Obsidian, re-paste the location of the .bib file in the plugin settings. Neither of these have triggered the plugin to recognize a new entry I just added. I had 8 entries in the file and it was working as expected. I added a 9th, and after the above workarounds the plugin still persistently said it only loaded eight. I can see the entry in the .bib file and the formatting looks correct. I noticed that particular entry had a long "annote" attribute, so I nixed that part of the entry completely directly in the .bib file to see if it was interfering with the plugin's ability to read the file. Now Obsidian recognizes there are 9 entries and it's pulling the new one correctly. In any case, my system details:

* macOS 11.2.3
* Obsidian 0.11.5 and Citations 0.4.1
* In developer console, I did also see errors with two other plugins (though the problem is resolved regardless):
  * "Cannot read property 'settings' of undefined, MinimalTheme.refreshSystemTheme (eval at evalFunc (app.js:1)" (for Minimal Theme plugin)
  * For Calendar plugin: "styles.css not found"

**Comment by Mara-Li** [comment] 2021-04-21 11:44
Windows 10, similar issue. For the moment, my work around is to change (remove .bib - re-add it) to update my library. 
I have no error in the console !

**Comment by npeschke** [comment] 2021-04-25 15:03
I encounter that issue as well
- Pop!_OS 20.04 LTS x86_64 Kernel: 5.11.0-7614-generic
- Obsidian v0.11.13
- Citations 0.4.2

My workaround is to open the developer console and use ctrl+r to reload obsidian. Afterwards it finds the new entries in the bib file. 

I also noticed that upon switching the database format to CSL-JSON and back to Biblatex, the bib file is read again and the new references are found.

**Comment by hans** [comment] 2021-04-30 19:00
Hi all, so sorry that this is a long-running issue for you all. Mysteriously, I am still unable to reproduce the issue on either Linux or Windows.

@npeschke I might ask for your help in your particular since we have very similar setups (though it would help if everyone reporting could check this) — can you please check the following?

1. Open any of the citation dialogs in Obsidian (e.g. insert citation link, open literature note link, etc.)
2. Update the configured .bib file, preferably directly, e.g. by opening with a text editor, adding a blank line somewhere, and saving
3. Watch for any change in the citation dialog. Within 1 second there should be a display like the one in the screenshot below.

If this doesn't work for you, then it looks like we have a problem with the filesystem watcher itself. Otherwise, it's something within the plugin.

Thanks & hope we can diagnose this quickly!

![2021-04-30_14-59](https://user-images.githubusercontent.com/6968/116741939-ab722200-a9c4-11eb-83ef-7fbd74290498.png)

**Comment by Mara-Li** [comment] 2021-05-02 13:17
I try, as @npeschke, but, like him, I don't have change in my bib.

**Comment by Benature** [comment] 2021-05-11 02:09
I tried, and like @npeschke and @Mara-Li, didn't see the display like the screenshot, on my windows and mac machine.

**Comment by brienna** [comment] 2021-05-26 00:53
My solution in Obsidian is to click on View > Force reload, then I'm able to see any info that I recently added to Zotero.

**Comment by yilu1015** [comment] 2021-05-29 14:27
> My solution in Obsidian is to click on View > Force reload, then I'm able to see any info that I recently added to Zotero.

This worked for me! (It will reload the entire bib file and display the following message for a few seconds: "Loading citation database. Please wait...")

Thanks for suggesting.

**Comment by lemywong** [comment] 2021-05-30 00:11
> My solution in Obsidian is to click on View > Force reload, then I'm able to see any info that I recently added to Zotero.

Thanks!
This works for me on Mac, unfortunately, it doesn't work for Win, as no 'refresh' button in Win.

**Comment by lemywong** [comment] 2021-05-30 00:20
> My solution in Obsidian is to click on View > Force reload, then I'm able to see any info that I recently added to Zotero.

Thanks!
It works for me on Mac, but not for Win, as no 'force reload' button in Win, but I manage to add a shortcut for 'reload the app without saving', it's something similar to reopen the app, but it's much convenient by using only the shortcut.

**Comment by bensleveritt** [comment] 2021-06-23 12:02
I'd like to add macOS (10.15) updating the .bib directly doesn't refresh the citation modal, so seems like the watcher for me.

I'd be tempted to load the bib file on modal creation, is that an option?

**Comment by hans** [comment] 2021-08-20 16:29
Hi all, there should be a fix for this issue in the just-released [v0.4.4](https://github.com/hans/obsidian-citation-plugin/releases/tag/0.4.4). Please update and let me know here if the issue is not resolved for you. Thanks for your extreme patience!

**Closed** 2021-08-20 16:29 UTC

**Comment by b-houghton** [comment] 2022-05-10 15:24
I am experiencing the same problem. I am using:

- Zotero 6.0.7
- Better BibTeX 6.7.1
- Obsidian 0.14.6
- Citations 0.4.4
- macOS 12.3

Better BibTeX is configured to export citations in BibLaTeX format and to re-export automatically when something changes. I have verified that the automatic export is working.

I tried the test that @hans [requested above](https://github.com/hans/obsidian-citation-plugin/issues/52#issuecomment-830310216): with the "Insert Markdown citation" popup open in Obsidian, I opened the exported BibLaTeX file in a text editor, added a blank line at the end, and saved the file. The appearance of the citation popup did not change, and Citations did not reload the citations. If I instead select View -> Force Reload in Obsidian as @Mara-Li mentioned, the citations are reloaded.

**Comment by AasishKumarSharma** [comment] 2022-07-23 22:49
### About the **Error Message** (**EM**):  
#### "Unable to access literature note. Please check that the literature note folder exists, or update the Citations plugin settings."

![Obsidian2_20220724](https://user-images.githubusercontent.com/15665815/180624796-d1e4a87e-2888-4b0d-b99d-ee04e837f2c4.JPG)

#### I found there might be a number of ways this error message could pop up:

1. As mentioned in the message, the Folder Structure with the "FolderName" might not exist in your Obsidian Vault, That should be the same as mentioned here: (in the plugin settings)
![image](https://user-images.githubusercontent.com/15665815/180624893-63001441-95cc-47f3-a330-703d5bbc51ee.png)
![image](https://user-images.githubusercontent.com/15665815/180625196-a016586d-72a9-4f35-b4bb-1b3c8574cbf0.png)


2. I found, that if any other settings are not properly working, like the template, if you have customized it in the plugin settings, then it will not show any error message for corrupted templates but would fail to insert citation throwing this error -> **EM**: 
![image](https://user-images.githubusercontent.com/15665815/180625245-03cd84a3-3baa-43e9-ab6b-a7cfe139eb6b.png)

Therefore, these are the kind of error-handling things which I find missing in the plugin.

**Comment by huaiyizhao** [comment] 2022-10-15 09:42
Same issue here but mine is even worse. Say I modify some notes of one paper in Zotero and Better Bibtex automatically updates the .bib file for me. I can see the changes in that file. But in Obsidian, `Refresh database` does not seem to do anything. I tried to relaunch the app but still, nothing happens. I have to **delete** the literature note and create it again so that it can show the notes properly.

**Comment by mnmcgowen** [comment] 2022-12-25 02:45
Hello, I am experiencing the same issue as @huaiyizhao, cannot see changes to notes from Zotero without deleting the literature note. I am using Obsidian 1.0.3, Citations 0.4.5, Mac OS 12.4

**Comment by orionpilot** [comment] 2022-12-28 16:40
@huaiyizhao @mnmcgowen `Refresh database` does not work like that. Say you add an entry to your `.bib` file. If you try to open a literature note for that new entry with Obsidian already open, the plugin won't be able to find it.  _That's_ when you `Refresh database`, as it reloads your `.bib` file. That command does not change file contents.

Unfortunately, refreshing _already created_ literature notes is, as far as I know, only possible by deleting and recreating the note, see #174.

**Comment by haroldship** [comment] 2023-05-31 07:28
I'm also experiencing the same issue as @huaiyizhao. My environment:
- Macbook Pro 16" 2019
- MacOS Ventura 13.3.1a
- ObsidianMD 1.3.4
- Citation Plugin 0.4.5

**Comment by Spuriosity1** [comment] 2023-12-01 14:00
I'm experiencing the original issue (namely, that the plugin does not recognise new citations in the betterBibTex database unless I force reload the viewer). My configuration:
- Macbook Air M1 2020
- MacOS Monterey 12.6.6
- ObsidianMD 1.4.16
- Citation Plugin 0.4.5

**Comment by orionpilot** [comment] 2023-12-03 20:49
@Spuriosity1 To get the plugin to recognize the new entries in the `.bib` database, you need to refresh the plugin with the `Refresh database` command. This also happens when you force reload Obsidian itself, which is what I think you say you are currently doing, and why you are seeing the reload without using the specific plugin command.
